---
- name: Install pip
  hosts: prod_server
  become: yes
  tasks:
  - name: Download get-pip.py
    get_url:
      url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
      dest: /tmp/get-pip.py

  - name: Install pip
    command: python /tmp/get-pip.py

