---
- name: Install and configure PostgreSQL
  hosts: prod_server
  become: true

  tasks:
  - name: Update package lists
    yum:
      name: "*"
      state: latest

  - name: Install PostgreSQL
    yum:
      name: postgresql
      state: present

  - name: Start and enable PostgreSQL service
    service:
      name: postgresql
      state: started
      enabled: true

  - name: Install python3 and pip3
    yum:
      name: python3
      state: present
  - name: Install pip3
    yum:
      name: python3-pip
      state: present




